/**
 * This file was generated by st-open-api
 */

import {http} from '../function/http';
import {openApi} from '../function/open-api';

export class TgMultiplechoiceService {

    tgMultiplechoiceController_getMultiplechoiceQs = async (): Promise<void> => {
    
        await http({
                method: 'GET',
                url: `${openApi.endpointUrl}/tg_multiplechoice/getMultiplechoice/{user_id}/{cat}/{lang}`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

    tgMultiplechoiceController_solveMultipleChoice = async (): Promise<void> => {
    
        await http({
                method: 'POST',
                url: `${openApi.endpointUrl}/tg_multiplechoice/solve/`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

}