/**
 * This file was generated by st-open-api
 */

import {http} from '../function/http';
import {openApi} from '../function/open-api';
import {IUserEntity} from '../interface/components/i-user-entity';

export class UserService {

    userControllerList = async (): Promise<void> => {
    
        await http({
                method: 'GET',
                url: `${openApi.endpointUrl}/user`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

    userControllerCreate = async (): Promise<void> => {
    
        await http({
                method: 'POST',
                url: `${openApi.endpointUrl}/user/create`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

    userControllerUpdate = async (body: IUserEntity): Promise<void> => {
    
        await http({
                method: 'PUT',
                url: `${openApi.endpointUrl}/user/{id}/update`,
                header: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(body),
            },
            openApi.requestInterceptor
        );
    };

    userControllerDelete = async (): Promise<void> => {
    
        await http({
                method: 'DELETE',
                url: `${openApi.endpointUrl}/user/{id}/delete`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

}