/**
 * This file was generated by st-open-api
 */
import {IUserDto} from './i-user-dto';
import {ITokenPayloadDto} from './i-token-payload-dto';

export interface ILoginPayloadDto {

    user: IUserDto;

    token: ITokenPayloadDto;

}