/**
 * This file was generated by st-open-api
 */
import {IUserDtoEnum} from '../../enumeration/i-user-dto-enum';

export interface IUserDto {

    firstName?: string;

    lastName?: string;

    role?: IUserDtoEnum;

    email?: string;

}