/**
 * This file was generated by st-open-api
 */

import {http} from '../function/http';
import {openApi} from '../function/open-api';
import {IUserLoginDto} from '../interface/components/i-user-login-dto';
import {ILoginPayloadDto} from '../interface/components/i-login-payload-dto';
import {IUserRegisterDto} from '../interface/components/i-user-register-dto';
import {IUserDto} from '../interface/components/i-user-dto';

export class AuthService {

    authControllerUserLogin = async (body: IUserLoginDto): Promise<ILoginPayloadDto> => {
    
        const response = await http({
                method: 'POST',
                url: `${openApi.endpointUrl}/auth/login`,
                header: {
                    Accept: 'application/json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(body),
            },
            openApi.requestInterceptor
        );
        return JSON.parse(response);
    };

    authControllerUserRegister = async (body: IUserRegisterDto): Promise<IUserDto> => {
    
        const response = await http({
                method: 'POST',
                url: `${openApi.endpointUrl}/auth/register`,
                header: {
                    Accept: 'application/json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(body),
            },
            openApi.requestInterceptor
        );
        return JSON.parse(response);
    };

}