/**
 * This file was generated by st-open-api
 */

import {http} from '../function/http';
import {openApi} from '../function/open-api';

export class IntroService {

    introControllerListAllQsByCatAndUser = async (): Promise<void> => {
    
        await http({
                method: 'GET',
                url: `${openApi.endpointUrl}/intro/startview/{id}/{lang}`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

    introControllerListLvl = async (): Promise<void> => {
    
        await http({
                method: 'GET',
                url: `${openApi.endpointUrl}/intro/{lvl}/{pageid}/{lang}`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

}