/**
 * This file was generated by st-open-api
 */

import {http} from '../function/http';
import {openApi} from '../function/open-api';

export class TgIntroService {

    tgIntroController_putUserTutorialFinishedAlternative = async (): Promise<void> => {
    
        await http({
                method: 'POST',
                url: `${openApi.endpointUrl}/tg_intro`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

}