/**
 * This file was generated by st-open-api
 */

import {http} from '../function/http';
import {openApi} from '../function/open-api';

export class TgModellingService {

    tgModellingController_getSpecificModellingQuestion = async (): Promise<void> => {
    
        await http({
                method: 'GET',
                url: `${openApi.endpointUrl}/tg_modelling/question/{id}/{lang}`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

    tgModellingController_solveSpecificModellingQuestion = async (): Promise<void> => {
    
        await http({
                method: 'POST',
                url: `${openApi.endpointUrl}/tg_modelling/solve/{lang}`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

    tgModellingController_getModQS = async (): Promise<void> => {
    
        await http({
                method: 'GET',
                url: `${openApi.endpointUrl}/tg_modelling/modellingQsWithRuleTest`,
                header: {
                },
            },
            openApi.requestInterceptor
        );
    };

}