/**
 * This file was generated by st-open-api
 */

export interface IModelPermissionDto {
  model_name?: string;

  model_xml?: string;

  id: string;

  model_version: number;

  can_read: boolean;
  can_write: boolean;
}
