/**
 * This file was generated by st-open-api
 */
import {IModelEntity} from './i-model-entity';
import {IUserEntity} from './i-user-entity';
import {IRoleEntity} from './i-role-entity';

export interface IPermissionEntity {

    model: IModelEntity;

    user: IUserEntity;

    role: IRoleEntity;

}