/**
 * This file was generated by st-open-api
 */

export interface IUserLoginDto {

    email: string;

    password: string;

}

export class IUserLoginDtoImpl implements IUserLoginDto {
    public email: string;
    public password: string;

    constructor( email: string,  password: string) {

    }
}
